### ISSUE TITLE
compatibility with other IC's

### ISSUE THREAD

**Issue by Seedler1981** [PaulStoffregen/SerialFlash#10]
Hi,  I have been looking every where for a library that will fit my needs.  This one sounds great, if I could get it to work with my setup.

My flash chip is the Spansion S25FL512S.  I am running an atmega328p on a breadboard with 8Mhz arduino boot loader.

I tried changing "#define CSCONFIG()  pinMode(6, OUTPUT)" to pin 10 with no success.  at the moment no sketches run.

Hope you can help

**Comment by PaulStoffregen** [comment]
Spansion S25FL512S should work, but only pin 6 is supported for the CS signal.
