### ISSUE TITLE
EraseEverything validation

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/SerialFlash#22]
It might be helpful if EraseEverything did some validation checks.  As it is, it says things are erased even if SPI is disconnected.  You might print the id[] and verify it's non-zero.  After erase, you could read page 0 and verify that it is 256  0xff's.  (of course, it could report 0xff's even if erase failed, but in my testing it seems to report 0's with disconnected/mis-wired SPI)

**Comment by FrankBoesing** [comment]
Better is to read all pages, or parts of them. a) The erasing could be interrupted by the user (disconnects usb too early), b) maybe he does not use SerialFlash

**Comment by FrankBoesing** [comment]
https://github.com/PaulStoffregen/SerialFlash/pull/26

returns capacity=0 for not-connected (or wrong cs etc) chips.

**Comment by manitou48** [comment]
frank's pull fixed it
