### ISSUE TITLE
FS structure

### ISSUE THREAD

**Issue by Dragon-Knight** [PaulStoffregen/SerialFlash#37]
Hello.
You couldn't on tell about structure of file system in more detail?
I have an idea to write the program for the computer that to program a chip of memory via the programmator.

**Comment by FrankBoesing** [comment]
Did you try https://github.com/FrankBoesing/TeensyTransfer ?

**Comment by Dragon-Knight** [comment]
I apologize, my knowledge of English very bad and probably I not correctly expressed...

I want to create the folder on the computer, to place in it all necessary files, to launch the program which I want to write and on an output to receive the RAW file which I will write in flash memory via the programmator then I will be able to use this library for operation with file system.

**Comment by FrankBoesing** [comment]
Yes, you can do that with TeensyTransfer.

There's a *.exe  (and executables for MAC / LINU)  and a Sketch.

https://forum.pjrc.com/threads/33859-TeensyTransfer?p=101306

**Comment by Dragon-Knight** [comment]
Thanks for the response.

But how I understood your library only for Teensy 3.x boards, i.e. for ARM microcontrollers?
My task to make for ATmega 328/644/1284 microcontrollers..., i.e. only AVR 8bit.

**Comment by FrankBoesing** [comment]
Okay, you're right.

**Comment by Dragon-Knight** [comment]
But....
OK, thanks!
