### ISSUE TITLE
Issue running RawHardwareTest code

### ISSUE THREAD

**Issue by haapeng** [PaulStoffregen/SerialFlash#46]
Hi mate, I using spansion s25fl512s f.memory and run the RawHardwareTest code but the test failed.
I attached the results and my circuit here,
[testing2.pdf](https://github.com/PaulStoffregen/SerialFlash/files/1108769/testing2.pdf)

**Comment by roy-zahor** [comment]
Same issue here when using W25Q80DV.
I get the exact same results (even the byte count is the same).

**Comment by PaulStoffregen** [comment]
This is the wrong place to ask for help.  Post your questions on the Arduino forum.

When you ask on the forum, show clear photos of how you've actually connected the hardware.  Nobody can help when you give no useful info.

Again, this issue tracker is *not* the place to ask for project help.  Ask on the forum.
