### ISSUE TITLE
confirmed winbond W25Q80BV works

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/SerialFlash#5]
I tested winbond W25Q80BV DIP (1 MB SPI flash) from sparkfun
 http://www.adafruit.com/product/1564
works with the examples.  to winbond ID  stuff in RawHardwareTest example I added
if (id[2] == 0x14) return "W25Q80BV";

**Comment by PaulStoffregen** [comment]
Thanks.  Added.
