### ISSUE TITLE
Query: Can I maintain a persistent file with SerialFlash?

### ISSUE THREAD

**Issue by psrawke** [PaulStoffregen/SerialFlash#52]
Hey, 
I went through the SerialFlash for Teensy and it looks amazing. But I have a query related to file write function.

In my application, there is a **persistent** file, where the **size** of the file will be **constant** throughout the programme, but **contents** of the file will be **changing** from time to time. 

As per [documentation](https://github.com/PaulStoffregen/SerialFlash#write-data), the contents of the file cannot be updated, only the unwritten portions of the file may be written.
>Several limitations apply to writing. Only previously unwritten portions of the file may be written. File sizes can never change. Writes may only be done within the file's original size.

Is there any other way to implement a persistent file with SerialFlash?

Thanks in advance,
Prasanna

**Comment by PaulStoffregen** [comment]
As for help on the forum.  Github issues are only for reporting bugs.
