### ISSUE TITLE
round up for string storage address off by 1

### ISSUE THREAD

**Issue by manitou48** [PaulStoffregen/SerialFlash#6]
In SerialFlashDirectory.cpp the rounding of the string storage address to a multiple of 4 is off by one.
Calculation should be 
straddr += string_length(straddr) + 1;

Discussions at https://forum.pjrc.com/threads/28505-Can-t-get-files-on-SPI-flash?p=72976

**Comment by PaulStoffregen** [comment]
fixed
https://github.com/PaulStoffregen/SerialFlash/commit/b53b2910a98b9576d0f28cbf8d55d2ee6758597b
