### ISSUE TITLE
Support for Adesto SPI Flash Chip

### ISSUE THREAD

**Issue by AKASHWORLD614** [PaulStoffregen/SerialFlash#65]
i have seen your library and used it in my project will this support the flash chip i am willing to use or no 

https://lcsc.com/product-detail/FLASH_Adesto-Technologies-AT25SF321-SHD-T_C226100.html

if not then please say to me one with 32mb or more from website LCSC

**Comment by FrankBoesing** [comment]
These are tested:

https://raw.githubusercontent.com/PaulStoffregen/SerialFlash/master/tests.txt

Am 17. Januar 2020 10:41:21 MEZ schrieb AKASHWORLD614 <notifications@github.com>:
>i have seen your library and used it in my project will this support
>the flash chip i am willing to use or no 
>
>https://lcsc.com/product-detail/FLASH_Adesto-Technologies-AT25SF321-SHD-T_C226100.html
>
>if not then please say to me one with 32mb or more from website LCSC
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulStoffregen/SerialFlash/issues/65

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by AKASHWORLD614** [comment]
what should replace size with in this code 

SerialFlash.createErasable(filename, size);

what is the difference between these two 
SerialFlash.create(filename, size);
                       &
SerialFlash.createErasable(filename, size);

can we expand size of file as data grows in erasable?

**Comment by FrankBoesing** [comment]
For questions, please use the forum.

**Comment by PaulStoffregen** [comment]
questions here:
https://forum.pjrc.com/
