### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by MiLeG** [PaulStoffregen/SerialFlash#71]
Greetings,

I would like to use this code in my project, but the terms of use are not defined by a license.
According to [this page](https://choosealicense.com/no-permission/#for-users), it's better to ask the owner to create a license instead of using unlicensed code.

(Might I suggest the  [MIT license](https://opensource.org/licenses/MIT))

Thanks for your time.

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/SerialFlash/blob/master/SerialFlash.h#L9
